apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: eap72-sample-tst
  namespace: eap72-samples
spec:
  type: GitHub
  pathname: https://github.com/schong7100/rhacm-test.git
