apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: test1-cluster
  namespace: user-test1
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      cluster: test1
